### ISSUE TITLE
how to have only one textview in the list view (activity_runtime_blur.xml)

### ISSUE THREAD

**Issue by vepak** [MoshDev/LikeYahooWeather#2]
I'm trying to load long text in the list view, but I just need to do once instead of repeating 50 times.

I tried to set return value to 1 for getCount() in BlurListAdpater.java, but I couldn't able to scroll to see the content. Could you please help me in achieving this.

Thank you for your time.

-Vamsi.

**Comment by MoshDev** [comment]
Really I don't have any idea about how you did this, but I assume there should be no problem in loading larger views than the listview height, and it should be scrollable...
